services:
  metricly:
    container_name: metricly_metricly
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config/config.yaml:/etc/metricly/config.yaml:ro
      # - /proc/stat:/proc/stat:ro
      # - /proc/meminfo:/proc/meminfo:ro
      # - /proc/diskstats:/proc/diskstats:ro
      # - /proc/net/dev:/mnt/metricly/dev:ro
      # - /proc/self/mounts:/mnt/metricly/mounts:ro
      - /:/host/root:ro
    environment:
      - HOSTNAME=${HOSTNAME}
      - PROC_CPU_STAT=/host/root/proc/stat
      - PROC_MEMORY_INFO=/host/root/proc/meminfo
      - PROC_NETWORK_DEV=/host/root/proc/net/dev
      - PROC_DISK_MOUNTS=/host/root/proc/mounts
      - PROC_DISK_STATS=/host/root/proc/diskstats
    network_mode: host

  prometheus:
    container_name: metricly_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    network_mode: host
    restart: always
    depends_on:
      - metricly

  grafana:
    container_name: metricly_grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./config/infrastructure.json:/var/lib/grafana/dashboards/infrastructure.json:ro
    network_mode: host
    restart: always
    depends_on:
      - prometheus
