services:
  metricly:
    container_name: metricly_metricly
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/metricly/config.yaml:/etc/metricly/config.yaml:ro
      - /proc/stat:/proc/stat:ro
      - /proc/meminfo:/proc/meminfo:ro
      - /proc/net/dev:/mnt/net_dev:ro
    environment:
      - HOSTNAME=${HOSTNAME}
      - PROC_NET_DEV=/mnt/net_dev
    network_mode: host

  prometheus:
    container_name: metricly_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    network_mode: host
    restart: always
    depends_on:
      - metricly

  grafana:
    container_name: metricly_grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/:ro
    network_mode: host
    restart: always
    depends_on:
      - prometheus
