version: "3.8"

services:
  metricly:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /etc/metricly/config.yaml:/etc/metricly/config.yaml:ro
      - /proc:/proc:ro
    environment:
      - HOSTNAME=${HOSTNAME}

  # prometheus:
  #   image: prom/prometheus:latest
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - monitoring
  #   restart: always

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - monitoring
  #   restart: always
