services:
  metricly:
    container_name: metricly_metricly
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080    
    volumes:
      - ./config/config.yaml:/etc/metricly/config.yaml:ro,z
      # - /proc/stat:/proc/stat:ro
      # - /proc/meminfo:/proc/meminfo:ro
      # - /proc/diskstats:/proc/diskstats:ro
      # - /proc/net/dev:/mnt/metricly/dev:ro
      # - /proc/self/mounts:/mnt/metricly/mounts:ro
      - /:/host/root:ro,rslave # Changes in the source (host) are reflected in the container, not vice-versa
    environment:
      - HOSTNAME=${HOSTNAME}
      - PROC_CPU_STAT=/host/root/proc/stat
      - PROC_MEMORY_INFO=/host/root/proc/meminfo
      - PROC_NETWORK_DEV=/host/root/proc/net/dev
      - PROC_DISK_MOUNTS=/host/root/proc/mounts
      - PROC_DISK_STATS=/host/root/proc/diskstats

  prometheus:
    container_name: metricly_prometheus
    image: quay.io/prometheus/prometheus:v2.36.2
    ports:
      - 9090:9090    
    volumes:
      - ./config/prometheus/:/etc/prometheus/:ro,z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'      
    restart: always
    depends_on:
      - metricly

  grafana:
    container_name: metricly_grafana
    image: docker.io/grafana/grafana:11.3.1
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/:ro,z
      - ./config/infrastructure.json:/var/lib/grafana/dashboards/infrastructure.json:ro,z
    restart: always
    depends_on:
      - prometheus
