global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'metricly'
    scrape_interval: 10s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets:
          - 'metricly:8080' # Target where your app exposes metrics
