global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'metricly'
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'metricly_metricly_1:8080' # Target where your app exposes metrics
