apiVersion: v1
kind: ConfigMap
metadata:
  name: metricly-config
  namespace: monitoring
data:
  config.yaml: |
    server:
      address: 0.0.0.0
      port: 8080
    prometheus:
      address: prometheus-service
      port: 9090
    interval: 10s
    debug: true
