apiVersion: v1
kind: Service
metadata:
  name: metricly
  namespace: monitoring
spec:
  selector:
    app: metricly
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP